server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Front
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /selectMenus/**
        - id: Store
          uri: http://localhost:8082
          predicates:
            - Path=/stores/**, 
        - id: Rider
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**, 
        - id: customer
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**, /orderStatuses/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Front
          uri: http://front:8080
          predicates:
            - Path=/orders/**, /selectMenus/**
        - id: Store
          uri: http://store:8080
          predicates:
            - Path=/stores/**, 
        - id: Rider
          uri: http://rider:8080
          predicates:
            - Path=/deliveries/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/orders/**, /orderStatuses/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
